name: build
on:
  push:
    paths-ignore: 
      - '*.md'
    branches: [ main ]
  
jobs:
  build:
    name: my job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
        node: [10, 12, 14]
        exclude:
            - os: macos-latest
              node: 10
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: \${{ matrix.node }} 
      - name: npm clean install
        run: npm ci 
      - name: build step
        run: npm run build --if-present
